# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cali', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
