# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cali', '0003_auto_20170830_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
