# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cali', '0005_auto_20170830_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
