# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cali', '0006_auto_20170830_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
