# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cali', '0008_auto_20170831_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
